spring:
  profiles:
    active: prod
  application:
    name: hello-consumer
---
server:
  port: 7081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        metadata:
          version: v1
          weight: 1
  profiles: dev

---
server:
  port: 17083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        metadata:
          version: v2
          weight: 8
  profiles: prod


